name: dart_verse
description: A sample command-line application.
publish_to: none
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.2
  lints: ^2.0.0
  test: ^1.21.0
dependencies:

  archive: ^3.3.7
  async: ^2.11.0
  crypto: ^3.0.3
  dart_jsonwebtoken: ^2.7.1
  dart_webcore: ^0.1.0
  dotenv: ^4.1.0
  encrypt: ^5.0.1
  google_sign_in: ^6.1.0
  hive: ^2.2.3
  html: ^0.15.3
  http: ^0.13.6
  json_annotation: ^4.8.1
  logger: ^1.3.0
  mailer: ^6.0.1
  mime: ^1.0.4
  mongo_dart: ^0.9.1
  path: ^1.8.3
  uuid: ^3.0.7

