name: auth_server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.2
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  crypto: ^3.0.3
  dart_jsonwebtoken: ^2.7.1
  dotenv: ^4.1.0
  json_annotation: ^4.8.1
  mongo_dart: ^0.9.1
  path: ^1.8.3
  serverpod: ^1.1.0
